# ***************************************
# Hollistic Parameters
# ***************************************

random_state: 42


# ***************************************
# Data Split Parameters
# ***************************************

target_column: "readmitted"
test_size: 0.3