# *****************************
# Hollistic Parameters
# *****************************

random_state: 42


# *****************************
# Hollistic Parameters
# *****************************

build_data_docs: False


# *****************************
# Data Split Parameters
# *****************************

target_column: "readmitted"
test_size: 0.3