# *****************************
# Hollistic Parameters
# *****************************

random_state: 42


# *****************************
# Data Split Parameters
# *****************************

target_label: "readmitted"
set_sizes: [0.6, 0.2, 0.2]  # need to use list otherwise using "()" will assume it's a string
stratify: True


# *****************************
# Data unit Tests Parameters
# before and after cleaning
# *****************************

# for both
build_data_docs: False

# before cleaning
raw_datasource_name: "raw_datasource"
raw_suite_name: "raw_suite"
raw_data_asset_name: "diabetic_data"

# after cleaning and feature engineering
clean_datasource_name: "clean_datasource"
clean_suite_name: "clean_suite"
X_train_cleaned_data_asset_name: "X_train_cleaned"
X_test_cleaned_data_asset_name: "X_test_cleaned"


# *****************************
# FE + Data Unit Tests
# Parameters
# *****************************

upload_to_feature_store: False

# *****************************
# Feature Selection Parameters
# *****************************

# can be "rfe" or "all" or "manual"
# if "manual" then specify the features in the list below
feature_selection: "all"
manual_features: []

fs_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 42

n_features: 12


# *****************************
# Model Selection Parameters
# *****************************

# TODO: change to 50
n_trials: 1 


# *****************************
# Model Prediction Parameters
# *****************************

predict_proba: False