# *****************************
# Hollistic Parameters
# *****************************

random_state: 42


# *****************************
# Data Split Parameters
# *****************************

target_column: "readmitted"
test_size: 0.3


# *****************************
# Data unit Tests Parameters
# before and after cleaning
# *****************************

# for both
build_data_docs: False

# before cleaning
raw_datasource_name: "raw_datasource"
raw_suite_name: "raw_suite"
raw_data_asset_name: "diabetic_data"

# after cleaning and feature engineering
clean_datasource_name: "clean_datasource"
clean_suite_name: "clean_suite"
X_train_cleaned_data_asset_name: "X_train_cleaned"
X_test_cleaned_data_asset_name: "X_test_cleaned"


# **********************************
# FE + Data Unit Tests Parameters
# **********************************

upload_to_feature_store: False
feature_selection: "rfe"

# **********************************
# Feature Selection
# **********************************
baseline_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 42


nr_features: 12